version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.12 /usr/local/share/virtualenvs/tap-appsflyer
            source /usr/local/share/virtualenvs/tap-appsflyer/bin/activate
            uv pip install -U pip setuptools wheel
            uv pip install .[dev]
            uv pip install pylint
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-appsflyer/bin/activate
            pip install pylint
            pylint tap_appsflyer -d C,R,W
      - add_ssh_keys
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-appsflyer/bin/activate
            uv pip install pytest coverage
            mkdir -p test_output
            coverage run --source=tap_appsflyer,tests/unittests -m pytest tests/unittests tests/mock_integration --junitxml=test_output/report.xml
            coverage xml -o coverage.xml
            coverage html
            coverage report -m --fail-under=99 | tee coverage.txt
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: coverage.xml
      - store_artifacts:
          path: coverage.txt
      - store_artifacts:
          path: htmlcov
      - run:
          name: 'Upload Coverage Report'
          command: |
            source /usr/local/share/virtualenvs/tap-appsflyer/bin/activate
            uv pip install codecov
            codecov --file=coverage.xml --flags=unittests
      - run:
          name: 'Integration Tests'
          command: |
            if [ "$USE_TAPTESTER" = "true" ]; then
              source /usr/local/share/virtualenvs/tap-tester/bin/activate
              uv pip install --upgrade awscli
              aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
              source dev_env.sh
              unset USE_STITCH_BACKEND
              run-test --tap=tap-appsflyer tests
            else
              source /usr/local/share/virtualenvs/tap-appsflyer/bin/activate
              uv pip install pytest
              python -m pytest tests/mock_integration/ -v
            fi


workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
